"""Initial migration

Revision ID: e3f6f97a7271
Revises: 
Create Date: 2026-03-02 16:07:31.027232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3f6f97a7271'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_decision', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_agent_id'), 'audit_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_audit_log_correlation_id'), 'audit_log', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('broker_ref', sa.String(length=128), nullable=True),
    sa.Column('instrument', sa.String(length=128), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('trigger_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('filled_qty', sa.Integer(), nullable=False),
    sa.Column('avg_fill_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('slippage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('signal_id', sa.String(length=64), nullable=True),
    sa.Column('risk_approval_id', sa.String(length=64), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instrument', sa.String(length=128), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('greeks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument')
    )
    op.create_table('strategy_registry',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('underlying', sa.String(length=32), nullable=False),
    sa.Column('regime_affinity', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('backtest_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('instrument', sa.String(length=128), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('slippage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('regime', sa.String(length=32), nullable=True),
    sa.Column('signal_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_log_strategy_id'), 'trade_log', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trade_log_trade_date'), 'trade_log', ['trade_date'], unique=False)
    op.create_table('strategy_performance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_slippage', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('regime_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_performance')
    op.drop_index(op.f('ix_trade_log_trade_date'), table_name='trade_log')
    op.drop_index(op.f('ix_trade_log_strategy_id'), table_name='trade_log')
    op.drop_table('trade_log')
    op.drop_table('strategy_registry')
    op.drop_table('positions')
    op.drop_table('orders')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_correlation_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_agent_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
